services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASS:-postgres}
      POSTGRES_DB: ${DB_NAME:-postgres}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    # На сервере скачает этот образ, локально сбилдит с этим именем
    image: ${DOCKER_USERNAME:-local}/bd_project:latest
    environment:
      DB_USER: ${DB_USER:-postgres}
      DB_PASS: ${DB_PASS:-postgres}
      DB_NAME: ${DB_NAME:-postgres}
      DB_HOST: db
      DB_PORT: 5432
      SECRET_KEY: ${SECRET_KEY:-"my_super_secret_key_change_me"}
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - uploads_data:/code/app/uploads

  caddy:
    image: caddy:2.7-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - app

volumes:
  postgres_data:
  caddy_data:
  caddy_config:
  uploads_data: