"""Init full db schema

Revision ID: 353c57db46eb
Revises: e77ca61239fa
Create Date: 2026-04-04 17:53:14.982121

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '353c57db46eb'
down_revision: Union[str, Sequence[str], None] = 'e77ca61239fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('defect_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('severity_level', sa.SmallInteger(), nullable=True),
    sa.Column('repair_priority', sa.String(length=20), nullable=True),
    sa.Column('typical_repair_cost', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.CheckConstraint("repair_priority IN ('low', 'medium', 'high', 'critical')", name='check_repair_priority'),
    sa.CheckConstraint('severity_level BETWEEN 1 AND 5', name='check_severity_level'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('equipment_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('systems',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('parent_system_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['parent_system_id'], ['systems.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=True),
    sa.Column('role', sa.String(length=30), nullable=True),
    sa.Column('department', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint("role IN ('driver', 'mechanic', 'foreman', 'admin')", name='check_user_role'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('defect_type_systems',
    sa.Column('defect_type_id', sa.Integer(), nullable=False),
    sa.Column('system_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['defect_type_id'], ['defect_types.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['system_id'], ['systems.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('defect_type_id', 'system_id')
    )
    op.create_table('equipment_models',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('manufacturer', sa.String(length=100), nullable=True),
    sa.Column('typical_lifespan_hours', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['type_id'], ['equipment_types.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('type_id', 'name', name='uq_equipment_model_name')
    )
    op.create_table('equipment_units',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model_id', sa.Integer(), nullable=False),
    sa.Column('vin', sa.String(length=50), nullable=True),
    sa.Column('reg_number', sa.String(length=50), nullable=True),
    sa.Column('manufacture_year', sa.SmallInteger(), nullable=True),
    sa.Column('current_hours', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('purchase_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint("status IN ('active', 'maintenance', 'repair', 'decommissioned')", name='check_equipment_status'),
    sa.ForeignKeyConstraint(['model_id'], ['equipment_models.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reg_number'),
    sa.UniqueConstraint('vin')
    )
    op.create_table('defects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('equipment_unit_id', sa.Integer(), nullable=False),
    sa.Column('defect_type_id', sa.Integer(), nullable=False),
    sa.Column('system_id', sa.Integer(), nullable=False),
    sa.Column('detected_at', sa.DateTime(), nullable=False),
    sa.Column('detected_by', sa.Integer(), nullable=True),
    sa.Column('hours_at_detection', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('diagnosis', sa.Text(), nullable=True),
    sa.Column('diagnosed_at', sa.DateTime(), nullable=True),
    sa.Column('diagnosed_by', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('repair_description', sa.Text(), nullable=True),
    sa.Column('repaired_at', sa.DateTime(), nullable=True),
    sa.Column('repaired_by', sa.Integer(), nullable=True),
    sa.Column('repair_cost', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('hours_spent_repair', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.Column('closure_comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint("status IN ('open', 'in_diagnosis', 'waiting_parts', 'in_repair', 'closed', 'write_off')", name='check_defect_status'),
    sa.ForeignKeyConstraint(['defect_type_id'], ['defect_types.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['detected_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['diagnosed_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['equipment_unit_id'], ['equipment_units.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['repaired_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['system_id'], ['systems.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_defects_detected_at'), 'defects', ['detected_at'], unique=False)
    op.create_index(op.f('ix_defects_equipment_unit_id'), 'defects', ['equipment_unit_id'], unique=False)
    op.create_index(op.f('ix_defects_hours_at_detection'), 'defects', ['hours_at_detection'], unique=False)
    op.create_index(op.f('ix_defects_status'), 'defects', ['status'], unique=False)
    op.create_table('scheduled_maintenance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('equipment_unit_id', sa.Integer(), nullable=False),
    sa.Column('maintenance_type', sa.String(length=50), nullable=False),
    sa.Column('planned_date', sa.Date(), nullable=False),
    sa.Column('planned_hours', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('actual_date', sa.Date(), nullable=True),
    sa.Column('actual_hours', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['equipment_unit_id'], ['equipment_units.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('defect_media',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('defect_id', sa.Integer(), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('file_type', sa.String(length=50), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), nullable=True),
    sa.Column('uploaded_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['defect_id'], ['defects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_defect_media_defect_id'), 'defect_media', ['defect_id'], unique=False)
    op.create_table('defect_status_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('defect_id', sa.Integer(), nullable=False),
    sa.Column('old_status', sa.String(length=20), nullable=True),
    sa.Column('new_status', sa.String(length=20), nullable=False),
    sa.Column('changed_at', sa.DateTime(), nullable=True),
    sa.Column('changed_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['changed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['defect_id'], ['defects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('defect_status_history')
    op.drop_index(op.f('ix_defect_media_defect_id'), table_name='defect_media')
    op.drop_table('defect_media')
    op.drop_table('scheduled_maintenance')
    op.drop_index(op.f('ix_defects_status'), table_name='defects')
    op.drop_index(op.f('ix_defects_hours_at_detection'), table_name='defects')
    op.drop_index(op.f('ix_defects_equipment_unit_id'), table_name='defects')
    op.drop_index(op.f('ix_defects_detected_at'), table_name='defects')
    op.drop_table('defects')
    op.drop_table('equipment_units')
    op.drop_table('equipment_models')
    op.drop_table('defect_type_systems')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    op.drop_table('systems')
    op.drop_table('equipment_types')
    op.drop_table('defect_types')
    # ### end Alembic commands ###
